[project]
name = "tunecontrol"
version = "0.1.0"
description = "Blackbox ontroller tuning benchmark problems"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "numpy>=1.26",
    "scipy>=1.11",
    "matplotlib",
    "tqdm",
    "torch>=2.2",
]

[project.optional-dependencies]
botorch = [
    "botorch==0.15.1",
]
dev = [
    "pytest",
    "ruff",
]
